packages = ["i3-wm", "i3lock", "i3status", "rofi", "arandr"]
shared_directories = ["i3_config"]
script = """
install -g ${ALMA_USER} -o ${ALMA_USER} -m 644 -D -T /shared_dirs/i3_config/i3_config /home/${ALMA_USER}/.config/i3/config
install -g ${ALMA_USER} -o ${ALMA_USER} -m 644 -D -T /shared_dirs/i3_config/i3status_config /home/${ALMA_USER}/.config/i3status/config
chown -R ${ALMA_USER}:${ALMA_USER} /home/${ALMA_USER}/.config/i3/
chown -R ${ALMA_USER}:${ALMA_USER} /home/${ALMA_USER}/.config/i3status/
"""
environment_variables = ["ALMA_USER"]
