packages = ["tmux"]
shared_directories = ["tmux_config"]
script = """
install -g ${ALMA_USER} -o ${ALMA_USER} -m 644 -D -T /shared_dirs/tmux_config/tmux.conf /home/${ALMA_USER}/.tmux.conf
"""
environment_variables = ["ALMA_USER"]
