packages = ["alacritty"]
shared_directories = ["alacritty_config"]
script = """
install -g ${ALMA_USER} -o ${ALMA_USER} -m 644 -D -T /shared_dirs/alacritty_config/alacritty.yml /home/${ALMA_USER}/.config/alacritty/alacritty.yml
chown -R ${ALMA_USER}:${ALMA_USER} /home/${ALMA_USER}/.config/alacritty/
"""
environment_variables = ["ALMA_USER"]
